[package]
name = "esp-xray"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io-async = { version = "0.6.1" }
embassy-sync = "0.5.0"
futures-lite = "2.2.0"
log = { version = "0.4.20", default-features = false, optional = true }
probe-rs = { path = "/projects/forks/probe-rs/probe-rs" }
critical-section = { version = "1.1", features = ["std"] }
pretty_env_logger = "0.5.0"

[features]
log = ["dep:log"]
